# -*- coding: utf-8-unix -*-
#+STARTUP: indent showall

* Super Mario Bros. for MSX

Super Mario Bros. (SMB1) is a video game for NES released on 1985 by NINTENDO.
- Super Mario Bros. [[https://www.nintendo.co.jp/software/smb1/index.html]]

This is an experimental, fan-made, incomplete, MSX version of SMB1 clone.
- *MADE FROM FULL SCRATCH, BUT...*
- *NOT LISENCED BY Nintendo Co.,Ltd.*
- *NO PRE-BUILT PLAYABLE GAME DISK IMAGE NOR ROM IMAGE IS INCLUDED IN THE REPOSITORY.*
- *DO NOT COPY, MODIFY, MERGE, PUBLISH, DISTRIBUTE, SUBLICENSE, AND/OR SELL FILES IN THIS REPOSITORY, DISK IMAGE, ROM IMAGE, AND/OR ANY ARTIFACTS, THAT MADE FROM FILES IN THIS REPOSITORY.*

Copyright (C) 1985 NINTENDO \\
Copyright (C) 2021 Daishi Mori (mori0091)


THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

[[https://www.youtube.com/watch?v=Lj5KaXntIz0][https://img.youtube.com/vi/Lj5KaXntIz0/0.jpg]]


* Pre-requisites

** Target Machine
- MSX2+
- MSXturboR


** Host Platform
- Ubuntu 20.04
- Ubuntu 21.xx (not tested)

Ofcourse, Ubuntu on *WSL* is okey. :smile: \\
(*WSL*: Windows Subsystem for Linux)


** Build tools
- SDCC ::
  Small Device C Compiler\\
  [[http://sdcc.sourceforge.net/]]

... and some popular standard Linux/Unix commands:
- ~find~, ~make~,
- and so on.


** Install instructions of Build tools

*Ubuntu*
#+begin_src shell
  sudo apt update
  sudo apt install build-essential
  sudo apt install sdcc
#+end_src

* Build instructions

The below makes the rom image ~smb1msx.rom~ into ~bin~ directory.
#+begin_src shell
  make
#+end_src

And for cleaning up:
#+begin_src shell
  make clean
#+end_src
